# Generated by Django 5.0.3 on 2024-06-04 10:50

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Allergins',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('town', models.CharField(max_length=60, null=True)),
                ('county', models.CharField(max_length=60, null=True)),
                ('eircode', models.CharField(max_length=8, null=True)),
                ('phone', models.CharField(max_length=60, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery', models.BooleanField(default=False, null=True)),
                ('delivery_fee', models.FloatField(default=4, null=True)),
                ('cart_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fulfilled', models.BooleanField(default=False, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('sku', models.CharField(default=uuid.uuid4, editable=False, max_length=200, unique=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('image_description', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200, null=True, unique=True)),
                ('max_quantity', models.IntegerField(default=10, null=True)),
                ('showing_in_shop', models.BooleanField(default=True, null=True)),
                ('contains_allergin', models.ManyToManyField(blank=True, related_name='contains', to='products.allergin')),
                ('may_contain_allergin', models.ManyToManyField(blank=True, related_name='may_contain', to='products.allergin')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='ShippingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('town', models.CharField(max_length=60, null=True)),
                ('county', models.CharField(max_length=60, null=True)),
                ('eircode', models.CharField(max_length=8, null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.order')),
            ],
            options={
                'verbose_name_plural': 'Shipping Information',
            },
        ),
    ]
